; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_sfx_place
	.word @sfx_ntsc_sfx_clear
	.word @sfx_ntsc_sfx_garbage
	.word @sfx_ntsc_menu_select_change

@sfx_ntsc_sfx_place:
	.byte $81,$56,$82,$03,$80,$3f,$89,$f0,$01,$81,$f8,$01,$81,$bf,$01,$81
	.byte $56,$01,$00
@sfx_ntsc_sfx_clear:
	.byte $81,$d5,$82,$00,$80,$3f,$89,$f0,$01,$81,$a9,$01,$81,$8e,$01,$81
	.byte $c9,$01,$81,$9f,$01,$81,$c9,$01,$81,$9f,$01,$81,$86,$01,$81,$bd
	.byte $01,$81,$96,$01,$81,$bd,$01,$81,$96,$01,$81,$7e,$01,$81,$b3,$01
	.byte $81,$8e,$01,$81,$b3,$01,$81,$8e,$01,$81,$77,$01,$81,$a9,$01,$81
	.byte $86,$01,$81,$a9,$01,$81,$86,$01,$81,$70,$01,$81,$9f,$01,$81,$7e
	.byte $01,$81,$9f,$01,$81,$7e,$01,$81,$6a,$01,$81,$96,$01,$81,$77,$01
	.byte $81,$96,$01,$81,$77,$01,$81,$64,$01,$81,$8e,$01,$81,$70,$01,$81
	.byte $8e,$01,$81,$70,$01,$81,$5e,$01,$81,$86,$01,$81,$6a,$01,$00
@sfx_ntsc_sfx_garbage:
	.byte $8a,$0f,$89,$3f,$05,$8a,$0c,$04,$8a,$0d,$04,$8a,$0a,$04,$8a,$0b
	.byte $03,$00
@sfx_ntsc_menu_select_change:
	.byte $8a,$0f,$89,$3f,$04,$00

.export sounds
