; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_sfx_place
	.word @sfx_ntsc_sfx_clear
	.word @sfx_ntsc_sfx_garbage
	.word @sfx_ntsc_menu_select_change
	.word @sfx_ntsc_menu_select

@sfx_ntsc_sfx_place:
	.byte $8a,$0f,$89,$3f,$04,$00
@sfx_ntsc_sfx_clear:
	.byte $81,$3f,$82,$01,$80,$3f,$89,$f0,$01,$81,$fd,$82,$00,$01,$81,$d5
	.byte $01,$81,$2d,$82,$01,$01,$81,$ef,$82,$00,$01,$81,$0c,$82,$01,$01
	.byte $81,$d5,$82,$00,$01,$81,$b3,$01,$81,$fd,$01,$81,$c9,$01,$81,$e1
	.byte $01,$81,$b3,$01,$81,$96,$01,$81,$d5,$01,$81,$a9,$01,$00
@sfx_ntsc_sfx_garbage:
	.byte $8a,$0f,$89,$3f,$05,$8a,$0c,$04,$8a,$0d,$04,$8a,$0a,$04,$8a,$0b
	.byte $03,$00
@sfx_ntsc_menu_select_change:
	.byte $87,$3a,$88,$02,$86,$8f,$89,$f0,$04,$00
@sfx_ntsc_menu_select:
	.byte $87,$bd,$88,$00,$86,$8f,$89,$f0,$04,$86,$80,$01,$87,$a9,$86,$8f
	.byte $04,$00

.export sounds
