; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses MMC5 expansion, you must set FAMISTUDIO_EXP_MMC5 = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Main Theme
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env5,@env6,@env0 ; 00 : Acoustic Grand Piano
	.word @env4,@env5,@env6,@env0 ; 01 : Instrument 1
	.word @env3,@env5,@env6,@env0 ; 02 : Beat
	.word @env2,@env5,@env6,@env0 ; 03 : Main

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cf,$cd,$cd,$cb,$cb,$c9,$c9,$c7,$c7,$c5,$c5,$c2,$c2,$c0,$00,$0f
@env2:
	.byte $00,$ce,$ce,$cf,$0b,$ce,$02,$cd,$02,$cc,$02,$cb,$02,$ca,$02,$c9,$02,$c8,$02,$c7,$02,$c6,$00,$15
@env3:
	.byte $00,$c9,$c8,$c5,$c5,$c3,$c3,$c1,$c0,$00,$08
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $9d, $76, $80, $29, $9d, $00, $99, $29, $9d, $00, $99, $29
	.byte $9b, $00, $9b, $29
@song0ref21:
	.byte $9b
@song0ref22:
	.byte $00, $9b
@song0ref24:
	.byte $22, $9d, $00, $99, $22, $9d, $00, $99, $22, $9b, $00, $9b, $22, $9b, $48
@song0ref39:
	.byte $00, $9b, $21, $9d, $00, $99, $21, $9d, $00, $99, $21, $9b, $00, $9b, $21
	.byte $41, $0d
	.word @song0ref21
	.byte $77, $24, $95, $00, $83, $25, $95, $00, $83, $48, $9d, $76, $27, $9d, $00, $99, $27, $9d, $00, $99, $27, $9b, $00, $9b
	.byte $27, $9b, $00, $9b, $27, $9d, $00, $99, $25, $9d, $00, $99, $25, $9b, $00, $9b, $25, $9b, $48, $00, $9b, $25, $9d, $00
	.byte $99, $25, $9d, $00, $99, $21, $9b, $00, $9b, $21, $9b
	.byte $41, $0a
	.word @song0ref39
	.byte $22, $9b, $00, $9b, $22, $9b, $48
	.byte $41, $09
	.word @song0ref22
	.byte $ff, $91
	.byte $41, $1d
	.word @song0ref24
	.byte $41, $20
	.word @song0ref21
	.byte $41, $20
	.word @song0ref21
	.byte $41, $20
	.word @song0ref21
	.byte $9b, $00, $ff, $ed, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $77, $80, $1d, $9d, $00, $99, $76, $1d, $9d, $00, $99, $1d, $9b, $00, $9b, $1d
@song0ref167:
	.byte $9b, $00, $9b
@song0ref170:
	.byte $77, $16, $9d, $00, $99, $76, $16, $9d, $00, $99, $16, $9b, $00, $9b, $16
@song0ref185:
	.byte $9b, $00, $9b, $77, $15, $9d, $00, $99, $76, $15, $9d, $00, $99, $15, $9b, $00, $9b, $15
	.byte $41, $0f
	.word @song0ref167
	.byte $75, $18, $9b, $19, $9b, $77, $1b, $9d, $00, $99, $76, $1b, $9d, $00, $99, $1b, $9b, $00, $9b, $1b, $9b, $00, $9b, $77
	.byte $1b, $9d, $00, $99, $76, $19, $9d, $00, $99, $19, $9b, $00, $9b, $19, $9b, $00, $9b, $77, $19, $9d, $00, $99, $76, $19
	.byte $9d, $00, $99, $15, $9b, $00, $9b, $15
	.byte $41, $0b
	.word @song0ref185
	.byte $16, $9b, $00, $9b, $16
	.byte $41, $0a
	.word @song0ref167
	.byte $ff, $91
	.byte $41, $1d
	.word @song0ref170
	.byte $41, $20
	.word @song0ref167
	.byte $41, $20
	.word @song0ref167
	.byte $41, $20
	.word @song0ref167
	.byte $9b, $00, $ff, $ff, $8b, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $78, $82
@song0ref298:
	.byte $29
@song0ref299:
	.byte $b9, $24, $99, $00, $25, $99, $00, $27, $b7, $00, $25, $97, $00, $81, $24, $97, $00, $81, $22, $b9, $22, $99, $00, $25
	.byte $99, $00, $29, $b7, $00, $27, $97, $00, $81, $25, $97, $00, $81, $24
	.byte $41, $0a
	.word @song0ref299
@song0ref340:
	.byte $29, $b7, $00, $25, $b9, $22, $b9, $22, $b7, $00, $bb, $bb, $27, $b9, $2a, $97, $00, $81, $2e, $b5, $00, $9f, $2c, $99
	.byte $00, $2a, $99, $00, $29, $f5, $25, $97, $00, $81, $29, $9b, $bb, $27, $99, $00, $25, $99, $00, $24, $d5, $00, $25, $97
	.byte $00, $81, $27, $b7, $00, $29, $b9, $25, $b7, $00, $22, $b7, $00, $22, $b9, $00, $ff, $b1
@song0ref406:
	.byte $29, $f5, $25, $f1, $00, $81, $27, $f5, $24, $f1, $00, $81, $25, $f5, $22, $f1, $00, $81, $21, $f5, $24, $f1, $00, $81
	.byte $41, $0d
	.word @song0ref406
@song0ref433:
	.byte $b9, $29, $b9, $2e, $f1, $00, $81, $2d, $ff, $eb, $00, $ff, $ef, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $84
@song0ref451:
	.byte $25, $9b, $23, $9b, $25, $9b, $23, $9b, $25, $9b, $23, $9b
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $25, $9b, $23, $9b, $00, $f5
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $41, $0c
	.word @song0ref451
	.byte $25, $9b, $23, $9b, $25, $9b, $23, $9b, $00, $ff, $ed, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref544:
	.byte $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df
	.byte $41, $0c
	.word @song0ref544
	.byte $41, $0c
	.word @song0ref544
	.byte $42
	.word @song0ch4loop
@song0ch5:
@song0ch5loop:
	.byte $78, $86
	.byte $41, $27
	.word @song0ref298
	.byte $41, $0a
	.word @song0ref299
	.byte $41, $5a
	.word @song0ref340
	.byte $41, $0d
	.word @song0ref406
	.byte $41, $0d
	.word @song0ref433
	.byte $42
	.word @song0ch5loop
@song0ch6:
@song0ch6loop:
	.byte $41, $0c
	.word @song0ref544
	.byte $41, $0c
	.word @song0ref544
	.byte $41, $0c
	.word @song0ref544
	.byte $42
	.word @song0ch6loop
